blueprint:
  name: Open door detection & alarm & notification
  description: Triggers one or more alarms when a door or window is opened.
    The alarm stops automatically after a configurable duration.
    Individual sensors can be excluded.
    An optional notification can be sent when the alarm is triggered.
  domain: automation
  input:
    alarms:
      name: (Required) Alarm(s) to trigger
      description: Select one or more alarm switches to activate when an opening is detected (e.g. switch.alarm_living_room_alarm).
      selector:
        target:
          entity:
            domain: switch

    alarm_duration:
      name: (Required) Alarm duration
      description: Duration before the alarm(s) stop automatically (default 15 minutes).
      default: 15
      selector:
        number:
          min: 1.0
          max: 120.0
          unit_of_measurement: minutes
          mode: slider
          step: 1.0

    exclude:
      name: Excluded Sensors
      description: Door sensors to exclude from triggering the alarm. Only entities are supported, devices must be expanded!
      default:
        entity_id: []
      selector:
        target:
          entity:
          - device_class:
            - door

    actions:
      name: Notification Actions
      description: >
        Notifications or similar to be run when the alarm is triggered.
        {{sensor}} is replaced with the name of the sensor that triggered the alarm.
      default: []
      selector:
        action: {}
  source_url: https://github.com/vgelot/ha-blueprints/blob/main/blueprints/automation/open_door_detection_alarm_and_notification/open_door_detection_alarm_and_notification.yaml

variables:
  exclude: !input exclude
  sensor: "{{ trigger.event.data.new_state.name }}"

trigger:
  - platform: event
    event_type: state_changed

condition:
  - condition: template
    value_template: >
      {{
        trigger.event.data.entity_id not in exclude.entity_id
        and state_attr(trigger.event.data.entity_id, 'device_class') == 'door'
        and trigger.event.data.new_state.state == 'on'
        and trigger.event.data.old_state.state == 'off'
      }}

action:
  - alias: Trigger alarms
    service: switch.turn_on
    target: !input alarms

  - alias: Send notifications
    choose: []
    default: !input actions

  - alias: Wait for configured duration
    delay:
      minutes: !input alarm_duration

  - alias: Turn off alarms
    service: switch.turn_off
    target: !input alarms

mode: restart
